/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as CrmLoginRouteImport } from './routes/crm.login'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedCrmClientsRouteImport } from './routes/_authenticated/crm.clients'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as ApiPublicEnquiryRouteImport } from './routes/api/public/enquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/crm/login',
  path: '/crm/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmClientsRoute = AuthenticatedCrmClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const ApiPublicEnquiryRoute = ApiPublicEnquiryRouteImport.update({
  id: '/api/public/enquiry',
  path: '/api/public/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/api/public/enquiry': typeof ApiPublicEnquiryRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/api/public/enquiry': typeof ApiPublicEnquiryRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/_authenticated/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/api/public/enquiry': typeof ApiPublicEnquiryRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/crm/login'
    | '/crm/clients'
    | '/crm/leads'
    | '/api/public/enquiry'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm/login'
    | '/crm/clients'
    | '/crm/leads'
    | '/api/public/enquiry'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/crm'
    | '/crm/login'
    | '/_authenticated/crm/clients'
    | '/_authenticated/crm/leads'
    | '/api/public/enquiry'
    | '/_authenticated/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CrmLoginRoute: typeof CrmLoginRoute
  ApiPublicEnquiryRoute: typeof ApiPublicEnquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/crm/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/clients': {
      id: '/_authenticated/crm/clients'
      path: '/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof AuthenticatedCrmClientsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/api/public/enquiry': {
      id: '/api/public/enquiry'
      path: '/api/public/enquiry'
      fullPath: '/api/public/enquiry'
      preLoaderRoute: typeof ApiPublicEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmClientsRoute: typeof AuthenticatedCrmClientsRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmClientsRoute: AuthenticatedCrmClientsRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CrmLoginRoute: CrmLoginRoute,
  ApiPublicEnquiryRoute: ApiPublicEnquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
